# Introduction to NumPy
### (c) Nuno António 2020-2022 v1.00
Not for sharing. This file is for class hands-on teaching

In [1]:
# Import the package
import numpy as np

In [45]:
# Let's create an np array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [46]:
# The type of np arrays is "ndarray"
type(a)

numpy.ndarray

In [47]:
# Arrays can have multiple dimensions
# 0
a = np.array(42)
a.shape

()

In [48]:
# 1 -D
b = np.array([1, 2, 3, 4, 5])
b.shape

(5,)

In [49]:
# 2D
c = np.array([[1, 2, 3], [4, 5, 6]])
c.shape

(2, 3)

In [50]:
# 3D
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
d.shape

(2, 2, 3)

In [51]:
# Dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [52]:
# Now for some matrices operations
# First a multiplication
x = [[1.2, 2.5], [3.2, 1.8], [1.1, 4.3]]
y = [[2.1, 0.8], [1.3, 2.5]]
np.dot(x,y)

array([[ 5.77,  7.21],
       [ 9.06,  7.06],
       [ 7.9 , 11.63]])

In [53]:
# Inverse of Y
np.linalg.inv(y)

array([[ 0.59382423, -0.19002375],
       [-0.3087886 ,  0.49881235]])

In [54]:
# Determinant of Y
np.linalg.det(y)

4.210000000000001

In [55]:
# Transpose of X
np.transpose(x)

array([[1.2, 3.2, 1.1],
       [2.5, 1.8, 4.3]])

In [56]:
# For aditional methods and complete reference check: https://numpy.org/doc/stable/reference/index.html